Destroy a Session (Aka logout)
saasbook/berkeley-food-collective pull request #9
Opened 2022-04-13 04:48 UTC by Roberto-Cardenas

### What
Added the functionality for destroying a session (aka logging out of the system). Modified necessary views, helpers, routes, and controller actions.

### How
Added a hamburger menu that when clicked displays a side menu with a link for logging out. Modified the controller action responsible for destroying a session as well as fixing the routing. Wrote some simple behavior tests.

2022-04-13 16:42 UTC, armandofox commented on app/helpers/sessions_helper.rb
> +    session[:user_id] = nil
a slightly more idiomatic way to do this is `session.delete(:user_id)` which removes the key entirely from the hash.

2022-04-13 16:46 UTC, armandofox requested changes

2022-04-13 16:46 UTC, armandofox commented on app/views/announcements/index.html.erb
> +    <div class = "container-fluid">
spaces around `=` signs are an antipattern for HTML.  it looks like these files were correct before but this error got introduced. pls clean up.

2022-04-13 16:46 UTC, armandofox commented on config/routes.rb
> +  get 'logout' => 'sessions#destroy'
unless there's a really good reason, "destructive" or actions with side effects (like logout) should be accessed via a `post` or some action other than `get`.  strongly suggest modifying the route and UI button accordingly.

2022-04-13 16:46 UTC, armandofox commented on features/session/logout.feature
> +    Given I should see "Announcements"
this is minor but for readability, you should be more careful about the use of Given, When, and Then.  Given sets up preconditions, When simluates a user action, Then asserts postconditions.  in my view, for readability, line 13 above should be And, and `Then I should  see "Announcements"` seems like it should be part of the background steps (to confirm the login actually happened).  also that will help with the scenario of lines 16-19 currently not making sense: "Given i should see 'announcmenets' and I follow 'log out'" doesn't make sense as a story.  let me know if this comment makes sense, if not i can elaborate.

2022-04-13 19:00 UTC, Roberto-Cardenas commented
@armandofox 
I think we are ready for re-review

2022-04-15 04:54 UTC, armandofox approved these changes
please confirm before i merge this:  i do not see tests for logout, have these been implemented?

2022-04-15 05:00 UTC, Roberto-Cardenas commented
Theres only behavior testing for logout its under features/session/logout.feature

2022-04-15 05:04 UTC, merged